services:
  ros-rrc-dev:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: compas_rrc_driver:local
    container_name: ros-rrc-dev
    environment:
      - ROS_HOSTNAME=ros-rrc-dev
      - ROS_MASTER_URI=http://ros-rrc-dev:11311
      - ROS_LANG_DISABLE=genlisp:gennodejs:geneus
      - ROBOT_IP=${ROBOT_IP:-host.docker.internal}
      - ROBOT_STREAMING_PORT=${ROBOT_STREAMING_PORT:-30101}
      - ROBOT_STATE_PORT=${ROBOT_STATE_PORT:-30201}
      - ROS_NAMESPACE=${ROS_NAMESPACE}
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - roslaunch
      - compas_rrc_driver
      - bringup.launch
      - robot_ip:=${ROBOT_IP:-host.docker.internal}
      - robot_streaming_port:=${ROBOT_STREAMING_PORT:-30101}
      - robot_state_port:=${ROBOT_STATE_PORT:-30201}
      - namespace:=${ROS_NAMESPACE}
