version: '3.8'
services:
  ros-rrc-dev:
    image: compasrrc/compas_rrc_driver:ros2
    container_name: ros-rrc-dev
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    ports:
      - "9090:9090"
      - "30101:30101"
      - "30201:30201"
    command:
      - ros2
      - launch
      - compas_rrc_driver
      - bringup.launch.py
      - robot_ip:=host.docker.internal
      - robot_streaming_port:=30101
      - robot_state_port:=30201
      - namespace:=rob1
    volumes:
      - ./logs:/root/ros2_ws/logs
