version: '3'
services:
  abb-driver-1:
    image: gramaziokohler/compas_rrc_driver
    container_name: abb-driver-1
    environment:
      - ROS_HOSTNAME=abb-driver-1
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - compas_rrc_driver
      - bringup.launch
      - robot_ip:=192.168.0.101        # NOTE: IP Address of the first robot controller
      - robot_streaming_port:=30101
      - robot_state_port:=30201
      - namespace:=robot1              # NOTE: Namespace of the first robot, to use when opening the connection from the client side

  abb-driver-2:
    image: gramaziokohler/compas_rrc_driver
    container_name: abb-driver-2
    environment:
      - ROS_HOSTNAME=abb-driver-2
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - compas_rrc_driver
      - bringup.launch
      - robot_ip:=192.168.0.102        # NOTE: IP Address of the second robot controller
      - robot_streaming_port:=30101    # NOTE: Streaming port can be the same for multiple robots on the multiple controllers
      - robot_state_port:=30201        # NOTE: State port can be the same for multiple robots on the multiple controllers
      - namespace:=robot2              # NOTE: Namespace of the second robot, to use when opening the connection from the client side

  ros-master:
    image: gramaziokohler/compas_rrc_driver
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/compas_rrc_driver
    container_name: ros-bridge
    environment:
      - ROS_HOSTNAME=ros-bridge
      - ROS_MASTER_URI=http://ros-master:11311
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
      - unregister_timeout:=28800      # This horribly long timeout of 8 hours is to workaround this issue: https://github.com/RobotWebTools/rosbridge_suite/issues/138
